### ISSUE TITLE
Categories Sensing, Operators, List not available in German

### ISSUE THREAD

**Issue by mslg** [janniklaval/phratch#204]
With German (de) enabled, clicking onto the categories 'Fühlen' (sensing), 'Operatoren' (operators) or 'Liste' (list) throws an error:
--------------------------------------------------------------------
MessageNotUnderstood: receiver of "method" is nil
UndefinedObject(Object)>>doesNotUnderstand: #method
CommandBlockMorph>>uncoloredArgMorphFor:
CommandBlockMorph>>argMorphFor:
CommandBlockMorph>>addLabel
CommandBlockMorph>>commandSpec:
CommandBlockMorph class(BlockMorph class)>>initBlock:on:withSpec:color:
PhratchSpriteMorph(ScriptablePhratchMorph)>>blockFromSpec:color:
PhratchSpriteMorph(ScriptablePhratchMorph)>>blocksFor: in Block: [ :spec | ...
Array(SequenceableCollection)>>do:
PhratchSpriteMorph(ScriptablePhratchMorph)>>blocksFor:
PhratchSpriteMorph(ScriptablePhratchMorph)>>addGenericListBlocksTo:y:
PhratchCategoryList class>>viewerPageFor:
PhratchSpriteMorph(ScriptablePhratchMorph)>>viewerPageForCategory:
PhratchViewerMorph>>updateContents
PhratchViewerMorph>>currentCategory:
ResizableToggleButton(SimpleButtonMorph)>>doButtonAction in Block: [ target perform: actionSelector withArguments: ar...etc...
BlockClosure>>ensure:
CursorWithMask(Cursor)>>showWhile:
ResizableToggleButton(SimpleButtonMorph)>>doButtonAction
ResizableToggleButton>>mouseUp:
ResizableToggleButton(Morph)>>handleMouseUp:
-------------------------------------------------------------------------------

Way to reproduce:
* select language 'de'
* choose 'Fühlen', 'Operatoren' or 'Liste' as category in the upper left area of the phratch-UI

Screenshot of debugger 
![messagenotunderstood receiver of method is nil](https://cloud.githubusercontent.com/assets/12203997/7438257/5e20fd0a-f061-11e4-8a6b-3329f1245d69.png)

**Comment by janniklaval** [comment]
It was a $Strings$ instead of $String$ in the file

**Comment by mslg** [comment]
es.po has a similar problem with operadores (operators)

I found some more typos in de.po:

 	msgid "date/time: $TimeDates$"
 	msgstr "Datum/Uhrzeit: $TimeDate$"

Should be $TimeDates$, I guess.

 	msgid "$Number$ is an integer?"
 	msgstr "Ist $Numnber$ ein Integer?"

Should be $Number$

 	msgid "is $String$ nil?"
 	msgstr "Ist $String% nil?"

Should be $String$

 	msgid "ask $String$ in dialog"
 	msgstr "Frage $String% in Dialog"

Should be $String$

 	msgid "$String$ as color"
 	msgstr "$String" als Farbe"

Should be $String$

 	msgid "mix $Color$ $Number$ : $Number$ with $Color$"
 	msgstr "Mische $Color$ $Number"$ : $Number$ mit $Color$"

Should be $Number$

 	msgid "attribute $Attributes$"
 	msgstr "Attribute $Attributes$"

Should be "Attribut $Attributes$"

 	msgid "create file $String$"
 	msgstr "Erzeuge Datei $String$"

Should be "erzeuge Datei $String$"

 	msgid "delete file $String$"
 	msgstr "Lösche Datei $String$"

Should be "lösche Datei $String$

 	msgid "clear file $String$"
 	msgstr "Lösche Datei $String$"

Should be "leere Datei $String$"

In general the first word of a German msgstr on a block should begin 
lowercase unless it's a noun, e.g.

 	"lösche..."
 	"setze..."
 	"erzeuge..."
 	"mische..."
 	"gehe..."
 	"ändere..."
 	"mache..."

Three strings are untranslated in de.po:

 	msgid "Block Editor"
 	msgstr ""

Suggested translation: "Block-Editor"

 	msgid "Text"
 	msgstr ""

Suggested translation: "Text"

 	msgid "New file name?"
 	msgstr ""

Suggested translation: "Neuer Dateiname?"

Some strings are missing in de.po, e.g.

* "make locale list $aList$"
* "neg" (operator)
* "delete variable $String$"
* "variable or list named $String$"
* "replace backgrund $Number$ with"
* "delete background $Number$
* "add ... to backgrounds"
* "change horizontal pan by $Number$"
* "change vertical pan by $Number$"
* "set horizontal pan to $Number$"
* "set vertical pan to $Number$"
* "select $String$ where"
* "change pen hue by $Number$"
* "set pen hue to $Number$"
* "stage minimum x"
* "stage maximum x"
* "stage minimum y"
* "stage maximum y"

Something is wrong with

 	msgid "$Number$ as integer"
 	msgstr "$Number$ als Integer"

This block shows up untranslated in any language.

Same problem exists for

 	msgid "$Number$ is an integer?"

I don't like

 	msgid "pen up"
 	msgstr "Stift hoch"

 	msgid "pen down"
 	msgstr "Stift runter"

 	msgid "pen down?"
 	msgstr "Stift unten?"

I know Jens prefers these (we had quite some discussion on this point), 
but it's different from all other blocks. In Scratch we changed it to

 	msgid "pen up"
 	msgstr "schalte Stift aus"

 	msgid "pen down"
 	msgstr "schalte Stift ein"

 	msgid "pen down?"
 	msgstr "Stift an?"

Markus

**Comment by janniklaval** [comment]
Could you change the files and send a pull request ?

Thank you for your messages.

Jannik

2015-05-03 0:17 GMT+02:00 mslg <notifications@github.com>:

> es.po has a similar problem with operadores (operators)
>
> I found some more typos in de.po:
>
> msgid "date/time: $TimeDates$"
> msgstr "Datum/Uhrzeit: $TimeDate$"
>
> Should be $TimeDates$, I guess.
>
> msgid "$Number$ is an integer?"
> msgstr "Ist $Numnber$ ein Integer?"
>
> Should be $Number$
>
> msgid "is $String$ nil?"
> msgstr "Ist $String% nil?"
>
> Should be $String$
>
> msgid "ask $String$ in dialog"
> msgstr "Frage $String% in Dialog"
>
> Should be $String$
>
> msgid "$String$ as color"
> msgstr "$String" als Farbe"
>
> Should be $String$
>
> msgid "mix $Color$ $Number$ : $Number$ with $Color$"
> msgstr "Mische $Color$ $Number"$ : $Number$ mit $Color$"
>
> Should be $Number$
>
> msgid "attribute $Attributes$"
> msgstr "Attribute $Attributes$"
>
> Should be "Attribut $Attributes$"
>
> msgid "create file $String$"
> msgstr "Erzeuge Datei $String$"
>
> Should be "erzeuge Datei $String$"
>
> msgid "delete file $String$"
> msgstr "Lösche Datei $String$"
>
> Should be "lösche Datei $String$
>
> msgid "clear file $String$"
> msgstr "Lösche Datei $String$"
>
> Should be "leere Datei $String$"
>
> In general the first word of a German msgstr on a block should begin
> lowercase unless it's a noun, e.g.
>
> "lösche..."
> "setze..."
> "erzeuge..."
> "mische..."
> "gehe..."
> "ändere..."
> "mache..."
>
> Three strings are untranslated in de.po:
>
> msgid "Block Editor"
> msgstr ""
>
> Suggested translation: "Block-Editor"
>
> msgid "Text"
> msgstr ""
>
> Suggested translation: "Text"
>
> msgid "New file name?"
> msgstr ""
>
> Suggested translation: "Neuer Dateiname?"
>
> Some strings are missing in de.po, e.g.
>
> * "make locale list $aList$"
> * "neg" (operator)
> * "delete variable $String$"
> * "variable or list named $String$"
> * "replace backgrund $Number$ with"
> * "delete background $Number$
> * "add ... to backgrounds"
> * "change horizontal pan by $Number$"
> * "change vertical pan by $Number$"
> * "set horizontal pan to $Number$"
> * "set vertical pan to $Number$"
> * "select $String$ where"
> * "change pen hue by $Number$"
> * "set pen hue to $Number$"
> * "stage minimum x"
> * "stage maximum x"
> * "stage minimum y"
> * "stage maximum y"
>
> Something is wrong with
>
> msgid "$Number$ as integer"
> msgstr "$Number$ als Integer"
>
> This block shows up untranslated in any language.
>
> Same problem exists for
>
> msgid "$Number$ is an integer?"
>
> I don't like
>
> msgid "pen up"
> msgstr "Stift hoch"
>
> msgid "pen down"
> msgstr "Stift runter"
>
> msgid "pen down?"
> msgstr "Stift unten?"
>
> I know Jens prefers these (we had quite some discussion on this point),
> but it's different from all other blocks. In Scratch we changed it to
>
> msgid "pen up"
> msgstr "schalte Stift aus"
>
> msgid "pen down"
> msgstr "schalte Stift ein"
>
> msgid "pen down?"
> msgstr "Stift an?"
>
> Markus
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/janniklaval/phratch/issues/204#issuecomment-98408869>.
>



-- 

~~Jannik Laval~~
École des Mines de Douai
Enseignant-chercheur
http://www.jannik-laval.eu
http://www.phratch.com
http://www.approchealpes.info
http://car.mines-douai.fr/

**Comment by mslg** [comment]
On Tue, 5 May 2015, janniklaval wrote:

> Could you change the files and send a pull request ?

How do I send a pull request? Sorry, but I don't have much experience with 
github.

Markus

**Comment by janniklaval** [comment]
You can use a git pull on the repository, or if you prefer, send me the
files and I will commit them.

Cheers,
Jannik

2015-05-05 23:39 GMT+02:00 mslg <notifications@github.com>:

> On Tue, 5 May 2015, janniklaval wrote:
>
> > Could you change the files and send a pull request ?
>
> How do I send a pull request? Sorry, but I don't have much experience with
> github.
>
> Markus
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/janniklaval/phratch/issues/204#issuecomment-99230750>.
>



-- 

~~Jannik Laval~~
École des Mines de Douai
Enseignant-chercheur
http://www.jannik-laval.eu
http://www.phratch.com
http://www.approchealpes.info
http://car.mines-douai.fr/
