### ISSUE TITLE
Crash Drag & Drop Block UHE: isExternalScriptsMorph

### ISSUE THREAD

**Issue by NicDeGraaf** [janniklaval/phratch#208]
Select a Block and drag it into the tab: script  right from it.

----------------------------STACK------------------------------------

PhratchScriptsMorph(Object)>>doesNotUnderstand: #isExternalScriptsMorph
CommandBlockMorph(BlockMorph)>>justDroppedInto:event:
PhratchScriptsMorph(Morph)>>handleDropMorph:
DropEvent>>sentTo:
PhratchScriptsMorph(Morph)>>handleEvent:
MorphicEventDispatcher>>dispatchDropEvent:with:
MorphicEventDispatcher>>handleDropMorph:
DropEvent>>sentTo:
[ ^ anEvent sentTo: self ] in MorphicEventDispatcher>>dispatchEvent:with: in Block: [ ^ anEvent sentTo: self ]
BlockClosure>>ensure:
MorphicEventDispatcher>>dispatchEvent:with:
PhratchScriptsMorph(Morph)>>processEvent:using:
MorphicEventDispatcher>>dispatchDropEvent:with:
MorphicEventDispatcher>>handleDropMorph:
DropEvent>>sentTo:
[ ^ anEvent sentTo: self ] in MorphicEventDispatcher>>dispatchEvent:with: in Block: [ ^ anEvent sentTo: self ]
BlockClosure>>ensure:
MorphicEventDispatcher>>dispatchEvent:with:
ScrollFrameMorph(Morph)>>processEvent:using:
MorphicEventDispatcher>>dispatchDropEvent:with:
MorphicEventDispatcher>>handleDropMorph:
DropEvent>>sentTo:
[ ^ anEvent sentTo: self ] in MorphicEventDispatcher>>dispatchEvent:with: in Block: [ ^ anEvent sentTo: self ]
BlockClosure>>ensure:
MorphicEventDispatcher>>dispatchEvent:with:
PhratchScriptEditorMorph(Morph)>>processEvent:using:
MorphicEventDispatcher>>dispatchDropEvent:with:
MorphicEventDispatcher>>handleDropMorph:
DropEvent>>sentTo:
[ ^ anEvent sentTo: self ] in MorphicEventDispatcher>>dispatchEvent:with: in Block: [ ^ anEvent sentTo: self ]

**Comment by janniklaval** [comment]
Ok, you can submit an issue in the github bugtracker. We need to check that.

Jannik

2015-09-07 21:39 GMT+02:00 NicDeGraaf <notifications@github.com>:

> Select a Block and drag it into the tab: script right from it.
>
> ----------------------------STACK------------------------------------
>
> PhratchScriptsMorph(Object)>>doesNotUnderstand: #isExternalScriptsMorph
> CommandBlockMorph(BlockMorph)>>justDroppedInto:event:
> PhratchScriptsMorph(Morph)>>handleDropMorph:
> DropEvent>>sentTo:
> PhratchScriptsMorph(Morph)>>handleEvent:
> MorphicEventDispatcher>>dispatchDropEvent:with:
> MorphicEventDispatcher>>handleDropMorph:
> DropEvent>>sentTo:
> [ ^ anEvent sentTo: self ] in MorphicEventDispatcher>>dispatchEvent:with:
> in Block: [ ^ anEvent sentTo: self ]
> BlockClosure>>ensure:
> MorphicEventDispatcher>>dispatchEvent:with:
> PhratchScriptsMorph(Morph)>>processEvent:using:
> MorphicEventDispatcher>>dispatchDropEvent:with:
> MorphicEventDispatcher>>handleDropMorph:
> DropEvent>>sentTo:
> [ ^ anEvent sentTo: self ] in MorphicEventDispatcher>>dispatchEvent:with:
> in Block: [ ^ anEvent sentTo: self ]
> BlockClosure>>ensure:
> MorphicEventDispatcher>>dispatchEvent:with:
> ScrollFrameMorph(Morph)>>processEvent:using:
> MorphicEventDispatcher>>dispatchDropEvent:with:
> MorphicEventDispatcher>>handleDropMorph:
> DropEvent>>sentTo:
> [ ^ anEvent sentTo: self ] in MorphicEventDispatcher>>dispatchEvent:with:
> in Block: [ ^ anEvent sentTo: self ]
> BlockClosure>>ensure:
> MorphicEventDispatcher>>dispatchEvent:with:
> PhratchScriptEditorMorph(Morph)>>processEvent:using:
> MorphicEventDispatcher>>dispatchDropEvent:with:
> MorphicEventDispatcher>>handleDropMorph:
> DropEvent>>sentTo:
> [ ^ anEvent sentTo: self ] in MorphicEventDispatcher>>dispatchEvent:with:
> in Block: [ ^ anEvent sentTo: self ]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/janniklaval/phratch/issues/208>.
>



-- 

~~Jannik Laval~~
Enseignant-chercheur
IUT Lumière <http://iut.univ-lyon2.fr/>, Université Lyon Lumière
<http://www.univ-lyon2.fr/>
laboratoire DISP <http://disp-lab.fr/>
http://www.jannik-laval.eu
http://www.phratch.com
http://www.approchealpes.info

**Comment by janniklaval** [comment]
fixed in 451

**Comment by NicDeGraaf** [comment]
That was fast :)

Nic
