### ISSUE TITLE
Slider unaligned

### ISSUE THREAD

**Issue by hilaire** [janniklaval/phratch#212]
GUI Sliders are unaligned
![assenceurs](https://cloud.githubusercontent.com/assets/1217542/22066482/6d2d14ee-dd8d-11e6-9d0c-f775e1fbfd1e.png)

**Comment by hilaire** [comment]
Here is a fix hopefully realigning the sliders.
[SliderShift.cs.zip](https://github.com/janniklaval/phratch/files/721897/SliderShift.cs.zip)

**Comment by janniklaval** [comment]
works fine, thank you.

**Comment by janniklaval** [comment]
in 460
