### ISSUE TITLE
Thumbnail view

### ISSUE THREAD

**Issue by hilaire** [janniklaval/phratch#220]
Thumbnail view of imported background are 8 bits color Form, it does not look nice, why not using a true color alternative (24 bits), it will look much better and modern.
![thumbnail](https://cloud.githubusercontent.com/assets/1217542/22145050/141de814-df00-11e6-87c9-ac0f754d7299.png)

**Comment by hilaire** [comment]
After analyzing code, problem comes from you use of ColorForm.
This class is pretty unwell named because it is restricted to 8bits depths.
So each time your are using 
ColorForm extent: extent depth: 16
You should use Form ....
I edit several place and improve it, but I still have some scenes thumbnail unice. Still digging.

**Comment by hilaire** [comment]
A changeset, to test of course.
[ThumbnailView.cs.zip](https://github.com/janniklaval/phratch/files/719229/ThumbnailView.cs.zip)

**Comment by janniklaval** [comment]
super,
Il reste un endroit où il y a du 8bits: dans l'import de costume. Le thumbnail est en 8 bits. Je n'ai pas trouvé encore la raison

**Comment by janniklaval** [comment]
in 460

**Comment by hilaire** [comment]
Le 23/01/2017 à 15:57, janniklaval a écrit :
> super,
> Il reste un endroit où il y a du 8bits: dans l'import de costume. Le
> thumbnail est en 8 bits. Je n'ai pas trouvé encore la raison

Il faut redémarrer Phratch
