### ISSUE TITLE
Resizable toggle button looks odd

### ISSUE THREAD

**Issue by hilaire** [janniklaval/phratch#221]
The down arrow of the file dialog resizable toggle button is misplaced. See bellow.
![resizabletogglebutton](https://cloud.githubusercontent.com/assets/1217542/22248145/8178e22a-e23d-11e6-9eaa-92b035e58949.png)

**Comment by hilaire** [comment]
Here a fix
[Fix221.cs.zip](https://github.com/janniklaval/phratch/files/734985/Fix221.cs.zip)

**Comment by janniklaval** [comment]
in 464
