### ISSUE TITLE
Warining deprecated method

### ISSUE THREAD

**Issue by hilaire** [janniklaval/phratch#222]
With Phratch installed on Pharo4, right clic on a sprite, then in the menu selecting parents... raise a Warning about a deprecated method:
"The method MenuMorph>>title: has been deprecated.
Use method addTitle: instead"

**Comment by janniklaval** [comment]
is it useful to insure the compatibility with pharo 4 ?
I think we should go to pharo 5

**Comment by hilaire** [comment]
For clarification, the bug occurs in Pharo5 as well.

**Comment by hilaire** [comment]
In #465.
I can commit in the repo, Youpi !
