### ISSUE TITLE
Sprites coordinates truncated with Andika font

### ISSUE THREAD

**Issue by hilaire** [janniklaval/phratch#223]
The layout need to be checked
![spritecoordintates](https://cloud.githubusercontent.com/assets/1217542/22364964/43115ef6-e475-11e6-8f5a-66011c8add3c.png)

**Comment by hilaire** [comment]
Here a fix
[Fix223.cs.zip](https://github.com/janniklaval/phratch/files/734909/Fix223.cs.zip)

**Comment by janniklaval** [comment]
in 464
