### ISSUE TITLE
Sprite coordinates and direction printed as float

### ISSUE THREAD

**Issue by hilaire** [janniklaval/phratch#224]
The playfield coordinates system is integer. 
Why do the sprite area show float rounded to 1 decimal for both the sprite coordinates and its direction?
Any reason, or should we just print it as Integer?

![Float](https://cloud.githubusercontent.com/assets/1217542/22364964/43115ef6-e475-11e6-8f5a-66011c8add3c.png)

**Comment by janniklaval** [comment]
We should print it as integer

**Comment by hilaire** [comment]
Fixed in #466
