### ISSUE TITLE
Right panel overlap

### ISSUE THREAD

**Issue by hilaire** [janniklaval/phratch#226]
When the right panel is in narrow mode, the mouse coordinates overlap over the three new sprites buttons, these buttons are not accessible anymore

![rightpanel](https://cloud.githubusercontent.com/assets/1217542/22403095/5ed7e1a2-e60d-11e6-88eb-b9fe900ec357.png)

**Comment by hilaire** [comment]
Moreover, the coordinates are printed as float but should be integer.

**Comment by hilaire** [comment]
Here is a fix for both issues in this ticket.
[Fix226.cs.zip](https://github.com/janniklaval/phratch/files/737575/Fix226.cs.zip)

**Comment by janniklaval** [comment]
in 464
