### ISSUE TITLE
Default costume with blur border

### ISSUE THREAD

**Issue by hilaire** [janniklaval/phratch#234]
The default costume (Phratch mascot) seems to use alpha transparency around its borders.
It looks badly on Phratch, there is a kind of unpleasant double borders around the robot when it is dragged around.

Here is a version of this costume without this unpleasant border. Please consider it for inclusion.
![defaultspritecostume](https://cloud.githubusercontent.com/assets/1217542/22585958/a7b7df9e-e9fa-11e6-98f6-78ca5930c432.png)

**Comment by janniklaval** [comment]
should be fixed if you load the new directory
